### ISSUE TITLE
Documentation link points to 404 website

### ISSUE THREAD

**Issue by ALTinners** [swri-robotics/novatel_gps_driver#105]
The readme currently has a link which points to 

http://docs.novatel.com/OEM7/Content/Logs/Log_Reference.htm

Which currently is 404'ing.

**Comment by pjreed** [comment]
Looks like they've rearranged their documentation a bit; that should probably be https://docs.novatel.com/OEM7/Content/Commands/CommandsLogs.htm now.

**Comment by danthony06** [comment]
Thanks for pointing this out, I have updated the link.
