### ISSUE TITLE
Can the driver be used in Ubuntu 20.04？

### ISSUE THREAD

**Issue by SunYM-hash** [swri-robotics/novatel_gps_driver#110]
Hello,
How do I install the driver with ros-noetic？
Thank you very mach.
yours,
Sun

**Comment by pjreed** [comment]
I'm actually a little surprised this hasn't been released in Ubuntu 20.04 / ROS Noetic; it compiles and all of the tests pass, and I don't think there's any reason why it wouldn't work.  Until it gets an official release, you should be able to just clone this and build it in your workspace.

@danthony06 , could you release this into Noetic?

**Comment by danthony06** [comment]
Yeah, this one slipped through. I'll try to release it tomorrow.

**Comment by danthony06** [comment]
@SunYM-hash I've issued a pull request for adding this to noetic, and it should be available shortly. You can see the progress here: https://github.com/ros/rosdistro/pull/32732.
