### ISSUE TITLE
IMU rate has note been configured; cannot produce sensor_msgs/Imu messages

### ISSUE THREAD

**Issue by Zillurcuet** [swri-robotics/novatel_gps_driver#111]
During the starting, I see this warning once. Then "CORRIMUDATA queue overflow" this warning continuously. I am unable to get any IMU data. I am using propack6 receiver with KVH1750 IMU.

**Comment by danthony06** [comment]
Hi, does your issue look similar to the problems in this thread?
https://github.com/swri-robotics/novatel_gps_driver/issues/98

**Comment by Zillurcuet** [comment]
According to the documentation of KVH1750 IMU, I set it to 200 and now it is working.
