### ISSUE TITLE
New release into Rolling

### ISSUE THREAD

**Issue by clalancette** [swri-robotics/novatel_gps_driver#119]
Hello!

It looks like novatel_gps_driver is failing to build in Rolling: https://build.ros2.org/view/Rbin_uN64/job/Rbin_uN64__novatel_gps_driver__ubuntu_noble_amd64__binary/ .

The good news is that it looks like this is already fixed in the sources by #116 .  Could you please do a new release of this package into at least Rolling, which will fix the error?  Thank you!

**Comment by danthony06** [comment]
@clalancette Thanks, I released 4.1.2 for Humble, Iron, and Rolling.

https://github.com/ros/rosdistro/pull/40246
https://github.com/ros/rosdistro/pull/40247
https://github.com/ros/rosdistro/pull/40248

**Comment by clalancette** [comment]
> @clalancette Thanks, I released 4.1.2 for Humble, Iron, and Rolling.

Thank you!
