### ISSUE TITLE
Set use_binary_messages to true will cause packets lost

### ISSUE THREAD

**Issue by shokaizhou** [swri-robotics/novatel_gps_driver#30]
I added use_binary_messages in launch file and set it to true, the rate of output imu data rate will lost about 1/3. Has someone met this problem before?

**Comment by pjreed** [comment]
I haven't seen this before; the message format should only be an issue if you are requesting messages at a rate that is higher than the supported bandwidth for your interface, but switching `use_binary_messages` to true should actually improve things in that situation.

What configuration are you using for the node?

**Comment by pjreed** [comment]
I'll close this since there hasn't been any feedback in several months.
