### ISSUE TITLE
novatel_gps_msgs not built before novatel_gps_driver

### ISSUE THREAD

**Issue by msmcconnell** [swri-robotics/novatel_gps_driver#34]
When trying to build this package as part of a larger workspace using catkin_make, I got the following error repeatedly. 
```
In file included from /opt/carma/src/CARMANovatelGpsDriver/novatel_gps_driver/src/novatel_gps.cpp:35:0:
/opt/carma/src/CARMANovatelGpsDriver/novatel_gps_driver/include/novatel_gps_driver/novatel_gps.h:47:36: fatal error: novatel_gps_msgs/Gpgga.h: No such file or directory
compilation terminated.
CARMANovatelGpsDriver/novatel_gps_driver/CMakeFiles/novatel_gps_driver.dir/build.make:62: recipe for target 'CARMANovatelGpsDriver/novatel_gps_driver/CMakeFiles/novatel_gps_driver.dir/src/novatel_gps.cpp.o' failed
make[2]: *** [CARMANovatelGpsDriver/novatel_gps_driver/CMakeFiles/novatel_gps_driver.dir/src/novatel_gps.cpp.o] Error 1
CMakeFiles/Makefile2:22174: recipe for target 'CARMANovatelGpsDriver/novatel_gps_driver/CMakeFiles/novatel_gps_driver.dir/all' failed
make[1]: *** [CARMANovatelGpsDriver/novatel_gps_driver/CMakeFiles/novatel_gps_driver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This suggests to me that the novatel_gps_msgs package was not built before the novatel_gps_driver. I found that if I built the novatel_gps_msgs package on its own first, then the novatel_gps_driver would build without issue. 

My development environment is Ubuntu 16.04, ROS Kinetic, cmake 3.5.1, gcc 5.4.0, Python 2.7.12 and Python 3.5.2

**Comment by msmcconnell** [comment]
Adding 
```
add_dependencies(${PROJECT_NAME} ${catkin_EXPORTED_TARGETS})
```
To the CMakeLists.txt file in the novatel_gps_driver package resolved my issue. 

I can put up a PR unless the repo maintainers only wish to support catkin_tools instead of catkin_make

**Comment by pjreed** [comment]
I'm surprised that that fails, actually; `novatel_gps_msgs` is passed into the `CATKIN_DEPENDS` list for `novatel_gps_driver`, which I thought would've been sufficient to make it build the msgs package first.  I only use catkin tools, but I've never seen any failures due to that in the official ROS build farm's builds.  Still, feel free to submit a PR if that fixes it for you.

**Comment by MikeZhu92** [comment]
I come up with the same issue and @msmcconnell 's solution works for me too.

**Comment by pjreed** [comment]
I noticed that you made a fix for it, so I'm going to go ahead and pull that in.  Thanks!

**Comment by msmcconnell** [comment]
Glad to contribute!
