### ISSUE TITLE
 gps_common::GPSStatus::STATUS_FIX

### ISSUE THREAD

**Issue by yamfeng** [swri-robotics/novatel_gps_driver#47]
Hi，In this novatel_gps_driver,I doubt that  both the "gps" and "fix"  topic  published do not show the status information correctly,
In the file novatel_message_extractor.cpp,  the status is assigned a value 
gps_fix->status.status = gps_common::GPSStatus::STATUS_FIX;
should it be changed with the gpgga infomation？

**Comment by pjreed** [comment]
Yes, I think the quality of the GPGGA log should be used to fill that in.
