### ISSUE TITLE
Foxy Release

### ISSUE THREAD

**Issue by JWhitleyWork** [swri-robotics/novatel_gps_driver#96]
I have verified that the `dashing-devel` branch of this repo builds without error (or even warning) on Foxy. Could we please get a Foxy release of this driver and messages?

**Comment by pjreed** [comment]
Sure thing, I meant to do that a while back and it just slipped my mind:
https://github.com/ros/rosdistro/pull/26842

**Comment by JWhitleyWork** [comment]
Thanks, PJ!
