### ISSUE TITLE
How does the `novatel_gps_node.cpp` source file generate?

### ISSUE THREAD

**Issue by zzzzzzli** [swri-robotics/novatel_gps_driver#99]
There is no main function in any source file in the directory `novatel_gps_driver/src/` , but when I build it with `catkin_make`, a main function source file named `novatel_gps_node.cpp` generates in the `build/novatel_gps_driver/
` directory, so does the corresponding executable `novatel_gps_node`. I wonder where does the file  `novatel_gps_node.cpp` come from. Thank you!

**Comment by danthony06** [comment]
I believe in https://github.com/swri-robotics/novatel_gps_driver/blob/master/novatel_gps_driver/CMakeLists.txt, the ```swri_nodelet_add_node()``` call on line 97 generates this during compilation.

**Comment by pjreed** [comment]
That's right; the driver is intended to be primarily used as a nodelet, and that's defined in `novatel_gps_driver/src/nodelets/novatel_gps_nodelet.cpp`.  The `swri_nodelet_add_node` CMake macro is a convenience function that generates a standalone node executable from a template (https://github.com/swri-robotics/marti_common/blob/master/swri_nodelet/nodelet.cpp.in), which is primarily useful for testing and debugging purposes.

**Comment by zzzzzzli** [comment]
OK, thank you very much.
